CREATE DATABASE IF NOT EXISTS `DATES` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8_general_ci;
USE `DATES`;

/*
CREATE TABLE `CLIENT` (
  `cotisationa` VARCHAR(42),
  PRIMARY KEY ()
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
*/

CREATE TABLE `COURS` (
  `idc` VARCHAR(42),
  `nomc` VARCHAR(42),
  `descc` VARCHAR(42),
  `typec` VARCHAR(42),
  `prix` VARCHAR(42),
  PRIMARY KEY (`idc`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

/*
CREATE TABLE `DATE` (
  `jma` VARCHAR(42),
  PRIMARY KEY (`jma`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
*/

/*
CREATE TABLE `HEURE` (
  `hh:mm:ss` VARCHAR(42),
  PRIMARY KEY (`hh:mm:ss`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
*/

/*
CREATE TABLE `IS_A` (
  `idp` VARCHAR(42),
  PRIMARY KEY (`idp`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
*/

CREATE TABLE `MONITEUR` (
  ,
  PRIMARY KEY ()
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `PERSONNE` (
  `idp` VARCHAR(42),
  `nomp` VARCHAR(42),
  `prenomp` VARCHAR(42),
  `ddn` VARCHAR(42),
  `poids` VARCHAR(42),
  `adressemail` VARCHAR(42),
  `adresse` VARCHAR(42),
  `numerotel` VARCHAR(42),
  `mdp` VARCHAR(42),
  PRIMARY KEY (`idp`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `PONEYS` (
  `idp` VARCHAR(42),
  `nomp` VARCHAR(42),
  `poidssup` VARCHAR(42),
  PRIMARY KEY (`idp`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `RESERVER` (
  `hh:mm:ss` VARCHAR(42),
  `jma` VARCHAR(42),
  `idc` VARCHAR(42),
  `idp` VARCHAR(42),
  `duree` VARCHAR(42),
  `a_paye` VARCHAR(42),
  PRIMARY KEY (`hh:mm:ss`, `jma`, `idc`, `idp`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE `IS_A` ADD FOREIGN KEY (`idp`) REFERENCES `PERSONNE` (`idp`);
ALTER TABLE `RESERVER` ADD FOREIGN KEY (`idp`) REFERENCES `PONEYS` (`idp`);
ALTER TABLE `RESERVER` ADD FOREIGN KEY (`idc`) REFERENCES `COURS` (`idc`);
-- ALTER TABLE `RESERVER` ADD FOREIGN KEY (`jma`) REFERENCES `DATE` (`jma`);
-- ALTER TABLE `RESERVER` ADD FOREIGN KEY (`hh:mm:ss`) REFERENCES `HEURE` (`hh:mm:ss`);